### PR TITLE
Fix defaulting to NullNode in RootNode#node_for_line

### LINKED ISSUE #186: v0.22.0 undefined method `call' for HamlLint::Tree::NullNode:Class
When we updated the `haml_lint` gem to v0.22.0 we started seeing this error.  Any ideas?

```
yarn haml_lint v0.21.3
$ SKIP_RAILS=true bundle exec rake haml_lint 
rake aborted!
haml-lint failed with exit code 70
/home/u4646/bundle/ruby/2.3.0/gems/haml_lint-0.22.0/lib/haml_lint/rake_task.rb:99:in `run_cli'
/home/u4646/bundle/ruby/2.3.0/gems/haml_lint-0.22.0/lib/haml_lint/rake_task.rb:87:in `block in define'
/home/u4646/bundle/ruby/2.3.0/gems/rake-12.0.0/exe/rake:27:in `<top (required)>'
/home/u4646/bundle/ruby/2.3.0/gems/bundler-1.13.7/lib/bundler/cli/exec.rb:74:in `load'
/home/u4646/bundle/ruby/2.3.0/gems/bundler-1.13.7/lib/bundler/cli/exec.rb:74:in `kernel_load'
/home/u4646/bundle/ruby/2.3.0/gems/bundler-1.13.7/lib/bundler/cli/exec.rb:27:in `run'
/home/u4646/bundle/ruby/2.3.0/gems/bundler-1.13.7/lib/bundler/cli.rb:332:in `exec'
/home/u4646/bundle/ruby/2.3.0/gems/bundler-1.13.7/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/home/u4646/bundle/ruby/2.3.0/gems/bundler-1.13.7/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/home/u4646/bundle/ruby/2.3.0/gems/bundler-1.13.7/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
/home/u4646/bundle/ruby/2.3.0/gems/bundler-1.13.7/lib/bundler/cli.rb:20:in `dispatch'
/home/u4646/bundle/ruby/2.3.0/gems/bundler-1.13.7/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
/home/u4646/bundle/ruby/2.3.0/gems/bundler-1.13.7/lib/bundler/cli.rb:11:in `start'
/home/u4646/bundle/ruby/2.3.0/gems/bundler-1.13.7/exe/bundle:34:in `block in <top (required)>'
/home/u4646/bundle/ruby/2.3.0/gems/bundler-1.13.7/lib/bundler/friendly_errors.rb:100:in `with_friendly_errors'
/home/u4646/bundle/ruby/2.3.0/gems/bundler-1.13.7/exe/bundle:26:in `<top (required)>'
/home/u4646/bundle/ruby/2.3.0/bin/bundle:22:in `load'
/home/u4646/bundle/ruby/2.3.0/bin/bundle:22:in `<main>'
Tasks: TOP => haml_lint
(See full trace by running task with --trace)
undefined method `call' for HamlLint::Tree::NullNode:Class
/home/u4646/bundle/ruby/2.3.0/gems/haml_lint-0.22.0/lib/haml_lint/tree/root_node.rb:18:in `find'
/home/u4646/bundle/ruby/2.3.0/gems/haml_lint-0.22.0/lib/haml_lint/tree/root_node.rb:18:in `node_for_line'
/home/u4646/bundle/ruby/2.3.0/gems/haml_lint-0.22.0/lib/haml_lint/linter/final_newline.rb:9:in `visit_root'
/home/u4646/bundle/ruby/2.3.0/gems/haml_lint-0.22.0/lib/haml_lint/haml_visitor.rb:40:in `safe_send'
/home/u4646/bundle/ruby/2.3.0/gems/haml_lint-0.22.0/lib/haml_lint/haml_visitor.rb:19:in `visit'
/home/u4646/bundle/ruby/2.3.0/gems/haml_lint-0.22.0/lib/haml_lint/linter.rb:28:in `run'
/home/u4646/bundle/ruby/2.3.0/gems/haml_lint-0.22.0/lib/haml_lint/runner.rb:84:in `block in collect_lints'
/home/u4646/bundle/ruby/2.3.0/gems/haml_lint-0.22.0/lib/haml_lint/runner.rb:83:in `map'
/home/u4646/bundle/ruby/2.3.0/gems/haml_lint-0.22.0/lib/haml_lint/runner.rb:83:in `collect_lints'
/home/u4646/bundle/ruby/2.3.0/gems/haml_lint-0.22.0/lib/haml_lint/runner.rb:119:in `process_file'
/home/u4646/bundle/ruby/2.3.0/gems/haml_lint-0.22.0/lib/haml_lint/runner.rb:108:in `block in process_files'
/home/u4646/bundle/ruby/2.3.0/gems/haml_lint-0.22.0/lib/haml_lint/runner.rb:107:in `each'
/home/u4646/bundle/ruby/2.3.0/gems/haml_lint-0.22.0/lib/haml_lint/runner.rb:107:in `process_files'
/home/u4646/bundle/ruby/2.3.0/gems/haml_lint-0.22.0/lib/haml_lint/runner.rb:132:in `report'
/home/u4646/bundle/ruby/2.3.0/gems/haml_lint-0.22.0/lib/haml_lint/runner.rb:23:in `run'
/home/u4646/bundle/ruby/2.3.0/gems/haml_lint-0.22.0/lib/haml_lint/cli.rb:92:in `scan_for_lints'
/home/u4646/bundle/ruby/2.3.0/gems/haml_lint-0.22.0/lib/haml_lint/cli.rb:51:in `act_on_options'
/home/u4646/bundle/ruby/2.3.0/gems/haml_lint-0.22.0/lib/haml_lint/cli.rb:23:in `run'
/home/u4646/bundle/ruby/2.3.0/gems/haml_lint-0.22.0/lib/haml_lint/rake_task.rb:97:in `run_cli'
/home/u4646/bundle/ruby/2.3.0/gems/haml_lint-0.22.0/lib/haml_lint/rake_task.rb:87:in `block in define'
/home/u4646/bundle/ruby/2.3.0/gems/rake-12.0.0/lib/rake/task.rb:250:in `block in execute'
/home/u4646/bundle/ruby/2.3.0/gems/rake-12.0.0/lib/rake/task.rb:250:in `each'
/home/u4646/bundle/ruby/2.3.0/gems/rake-12.0.0/lib/rake/task.rb:250:in `execute'
/home/u4646/bundle/ruby/2.3.0/gems/rake-12.0.0/lib/rake/task.rb:194:in `block in invoke_with_call_chain'
/home/tddium/.rbenv/versions/2.3.3/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
/home/u4646/bundle/ruby/2.3.0/gems/rake-12.0.0/lib/rake/task.rb:187:in `invoke_with_call_chain'
/home/u4646/bundle/ruby/2.3.0/gems/rake-12.0.0/lib/rake/task.rb:180:in `invoke'
/home/u4646/bundle/ruby/2.3.0/gems/rake-12.0.0/lib/rake/application.rb:152:in `invoke_task'
/home/u4646/bundle/ruby/2.3.0/gems/rake-12.0.0/lib/rake/application.rb:108:in `block (2 levels) in top_level'
/home/u4646/bundle/ruby/2.3.0/gems/rake-12.0.0/lib/rake/application.rb:108:in `each'
/home/u4646/bundle/ruby/2.3.0/gems/rake-12.0.0/lib/rake/application.rb:108:in `block in top_level'
/home/u4646/bundle/ruby/2.3.0/gems/rake-12.0.0/lib/rake/application.rb:117:in `run_with_threads'
/home/u4646/bundle/ruby/2.3.0/gems/rake-12.0.0/lib/rake/application.rb:102:in `top_level'
/home/u4646/bundle/ruby/2.3.0/gems/rake-12.0.0/lib/rake/application.rb:80:in `block in run'
/home/u4646/bundle/ruby/2.3.0/gems/rake-12.0.0/lib/rake/application.rb:178:in `standard_exception_handling'
/home/u4646/bundle/ruby/2.3.0/gems/rake-12.0.0/lib/rake/application.rb:77:in `run'
/home/u4646/bundle/ruby/2.3.0/gems/rake-12.0.0/exe/rake:27:in `<top (required)>'
/home/u4646/bundle/ruby/2.3.0/bin/rake:22:in `load'
/home/u4646/bundle/ruby/2.3.0/bin/rake:22:in `<top (required)>'
/home/u4646/bundle/ruby/2.3.0/gems/bundler-1.13.7/lib/bundler/cli/exec.rb:74:in `load'
/home/u4646/bundle/ruby/2.3.0/gems/bundler-1.13.7/lib/bundler/cli/exec.rb:74:in `kernel_load'
/home/u4646/bundle/ruby/2.3.0/gems/bundler-1.13.7/lib/bundler/cli/exec.rb:27:in `run'
/home/u4646/bundle/ruby/2.3.0/gems/bundler-1.13.7/lib/bundler/cli.rb:332:in `exec'
/home/u4646/bundle/ruby/2.3.0/gems/bundler-1.13.7/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/home/u4646/bundle/ruby/2.3.0/gems/bundler-1.13.7/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/home/u4646/bundle/ruby/2.3.0/gems/bundler-1.13.7/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
/home/u4646/bundle/ruby/2.3.0/gems/bundler-1.13.7/lib/bundler/cli.rb:20:in `dispatch'
/home/u4646/bundle/ruby/2.3.0/gems/bundler-1.13.7/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
/home/u4646/bundle/ruby/2.3.0/gems/bundler-1.13.7/lib/bundler/cli.rb:11:in `start'
/home/u4646/bundle/ruby/2.3.0/gems/bundler-1.13.7/exe/bundle:34:in `block in <top (required)>'
/home/u4646/bundle/ruby/2.3.0/gems/bundler-1.13.7/lib/bundler/friendly_errors.rb:100:in `with_friendly_errors'
/home/u4646/bundle/ruby/2.3.0/gems/bundler-1.13.7/exe/bundle:26:in `<top (required)>'
/home/u4646/bundle/ruby/2.3.0/bin/bundle:22:in `load'
/home/u4646/bundle/ruby/2.3.0/bin/bundle:22:in `<main>'
Report this bug at https://github.com/brigade/haml-lint/issues

To help fix this issue, please include:
- The above stack trace
- Haml-Lint version: 0.22.0
- Haml version: 4.0.7
- RuboCop version: 0.47.1
- Ruby version: 2.3.3
error Command failed with exit code 1.
```

### PR DESCRIPTION
**Pull request by trotzig**
I don't have a lot of context on this but of code, other than it was
added in 4c95e3b5 to allow nodes to be disableable via comments.

When running haml-lint on a local project, I ran into the same issue as
was described in #186:

```
  undefined method `call' for HamlLint::Tree::NullNode:Class
  /Users/henrictrotzig/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/haml_lint-0.22.1/lib/haml_lint/tree/root_node.rb:18:in
  `find'
```

Making the first argument to `find` a lambda (or a proc) fixed the
issue.

Fixes #186

### CODE REVIEW

**Comment by trotzig** [comment]
Ping @michaelherold, perhaps you can help me come up with a good test for this?

**Comment by eitoball** [comment]
I was working on the same error. How about this https://github.com/eitoball/haml-lint/blob/fix-when-tree-is-empty/spec/haml_lint/tree/root_node_spec.rb ?

**Comment by michaelherold** [comment]
Ah, yes. That makes sense. I like @eitoball's test as well. Good find!

One nitpick: since it's a single-line I think the stabby proc syntax would be best: `find(-> { HamlLint::Tree::NullNode.new })`

**Comment by michaelherold** [comment]
As an integration test, we can try running something against a blank file. That's the only thing I can think of that would cause there to be no root node.

**Comment by trotzig** [comment]
I pushed the fix by @eitoball instead of mine in 405a153. Thanks for making a proper fix @eitoball! FYI, I did update the commit message before pushing, but you're still the author of the commit.

**Comment by eitoball** [comment]
Thank you for merging and releasing new version. 😄
